export function GetLanguageOptions(): { data: string; label: string }[] {
  return Object.keys(LOCALIZATION).map((key) => ({
    data: key,
    label: LOCALIZATION[key as keyof typeof LOCALIZATION].languageName,
  }));
}

export function Localize(language: string, key: string): string {
  try {
    const localization = LOCALIZATION as Record<string, Record<string, string>>;
    return localization[language]?.[key] ?? localization.English?.[key] ?? key;
  } catch {
    return key;
  }
}

const LOCALIZATION = {
    "English": {
        "languageName": "English",
        "LanguageOfPlugin": "Language of plugin",
        "NewsCount": "News count",
        "NewsCountDescription": "How many RSS news blocks are shown in the feed",
        "AlternateEveryNBlocks": "Alternate RSS news and regular Steam news every N blocks",
        "AlternateEveryNBlocksDescription": "Interval between RSS news and Steam news",
        "NewsBlocksRange": "Number of consecutive RSS news blocks",
        "NewsBlocksRangeDescription": "Number of consecutive RSS news blocks to insert",
        "HighliteEnglishLetters": "Highlight english letters",
        "HighliteEnglishLettersDescription": "Whether to highlight English letters within headlines (useful if the news is not in English)",
        "HighliteEnglishLettersColor": "Highlight english letters color (default: #ffffff)",
        "HighliteNumbers": "Highlight numbers",
        "HighliteNumbersDescription": "Whether to highlight numbers within headlines",
        "HighliteNumbersColor": "Highlight numbers color (default: #ffffff)",
        "HighliteQuotes": "Highlight quotes",
        "HighliteQuotesDescription": "Whether to highlight text enclosed in quotation marks within headlines",
        "HighliteQuotesColor": "Highlight quotes color (default: #ffffff)",
        "ImagesHeight": "Images height",
        "ImagesHeightDescription": "If your images are incorrect, set a different value here (you probably need to set it to 175) (default 135)",
        "RSSFeedLink": "RSS feed link",
        "RSSFeedLinkDescription": "Selecting a news source. Can be entered manually by selecting the 'other' option",
        "CustomRSSLink": "Custom RSS link",
        "CustomRSSLinkDescription": "You can insert your own link into your RSS feed. If something is not displayed correctly, please notify the plugin developer.",
        "Other": "other",
        "RSSNewsTitle": "RSS News",
        "UpdateRSSNews": "Update RSS news",
        "ScrollSpeed": "Scroll speed",
        "ScrollSpeedDescription": "Speed of automatic horizontal scrolling of the What's New feed (0 disables auto-scroll, max 10)"
    },
    "Russian": {
        "languageName": "Русский",
        "LanguageOfPlugin": "Язык плагина",
        "NewsCount": "Количество новостей",
        "NewsCountDescription": "Сколько блоков RSS новостей показывается в ленте",
        "AlternateEveryNBlocks": "Чередовать RSS новости и обычные Steam новости каждые N блоков",
        "AlternateEveryNBlocksDescription": "Интервал между новостями RSS и Steam новостями",
        "NewsBlocksRange": "Количество блоков RSS новостей, идущих подряд",
        "NewsBlocksRangeDescription": "Количество последовательных блоков RSS новостей для вставки",
        "HighliteEnglishLetters": "Выделение английских букв",
        "HighliteEnglishLettersDescription": "Выделять английские буквы в заголовках (полезно, если новости не на английском)",
        "HighliteEnglishLettersColor": "Цвет выделенных английских букв (по умолчанию: #ffffff)",
        "HighliteNumbers": "Выделение чисел",
        "HighliteNumbersDescription": "Выделять числа в заголовках",
        "HighliteNumbersColor": "Цвет выделения чисел (по умолчанию: #ffffff)",
        "HighliteQuotes": "Выделение текста в кавычках",
        "HighliteQuotesDescription": "Выделять текст в кавычках в заголовках",
        "HighliteQuotesColor": "Цвет выделения текста в кавычках (по умолчанию: #ffffff)",
        "ImagesHeight": "Высота изображений",
        "ImagesHeightDescription": "Если изображения отображаются неправильно, задайте другое значение (скорее всего, подойдет 175) (по умолчанию 135)",
        "RSSFeedLink": "Ссылка на RSS ленту",
        "RSSFeedLinkDescription": "Выбор источника новостей. Можно ввести вручную, выбрав вариант 'другое'",
        "CustomRSSLink": "Пользовательская RSS ссылка",
        "CustomRSSLinkDescription": "Вы можете вставить свою ссылку на источник RSS. Если что-то отображается некорректно, сообщите разработчику плагина.",
        "Other": "другое",
        "RSSNewsTitle": "RSS Новость",
        "UpdateRSSNews": "Обновить RSS новости",
        "ScrollSpeed": "Скорость прокрутки",
        "ScrollSpeedDescription": "Скорость автоматической горизонтальной прокрутки ленты \"Что нового\" (0 отключает автопрокрутку, максимум 10)"
      },
      "ChineseSimplified": {
        "languageName": "简体中文",
        "LanguageOfPlugin": "插件语言",
        "NewsCount": "新闻数量",
        "NewsCountDescription": "信息流中显示的 RSS 新闻块数量",
        "AlternateEveryNBlocks": "每 N 个块在 RSS 新闻和 Steam 新闻之间交替",
        "AlternateEveryNBlocksDescription": "RSS 新闻与 Steam 新闻之间的间隔",
        "NewsBlocksRange": "连续 RSS 新闻块数量",
        "NewsBlocksRangeDescription": "要插入的连续 RSS 新闻块数量",
        "HighliteEnglishLetters": "高亮英文字符",
        "HighliteEnglishLettersDescription": "是否在标题中高亮英文字符（当新闻不是英文时很有用）",
        "HighliteEnglishLettersColor": "高亮英文字符颜色（默认: #ffffff）",
        "HighliteNumbers": "高亮数字",
        "HighliteNumbersDescription": "是否在标题中高亮数字",
        "HighliteNumbersColor": "高亮数字颜色（默认: #ffffff）",
        "HighliteQuotes": "高亮引号内文本",
        "HighliteQuotesDescription": "是否在标题中高亮引号内文本",
        "HighliteQuotesColor": "引号内文本高亮颜色（默认: #ffffff）",
        "ImagesHeight": "图片高度",
        "ImagesHeightDescription": "如果图片显示不正确，请在此设置其他值（你可能需要设置为 175）（默认 135）",
        "RSSFeedLink": "RSS 订阅链接",
        "RSSFeedLinkDescription": "选择新闻来源。选择“其他”后可手动输入",
        "CustomRSSLink": "自定义 RSS 链接",
        "CustomRSSLinkDescription": "你可以插入自己的 RSS 来源链接。如果显示不正确，请联系插件开发者。",
        "Other": "其他",
        "RSSNewsTitle": "RSS 新闻",
        "UpdateRSSNews": "更新 RSS 新闻",
        "ScrollSpeed": "滚动速度",
        "ScrollSpeedDescription": "“新内容”栏自动水平滚动的速度（0 表示禁用自动滚动，最大值为 10）"
      },
      "Spanish": {
        "languageName": "Español",
        "LanguageOfPlugin": "Idioma del plugin",
        "NewsCount": "Cantidad de noticias",
        "NewsCountDescription": "Cuántos bloques de noticias RSS se muestran en el feed",
        "AlternateEveryNBlocks": "Alternar noticias RSS y noticias normales de Steam cada N bloques",
        "AlternateEveryNBlocksDescription": "Intervalo entre noticias RSS y noticias de Steam",
        "NewsBlocksRange": "Cantidad de bloques de noticias RSS consecutivos",
        "NewsBlocksRangeDescription": "Cantidad de bloques de noticias RSS consecutivos para insertar",
        "HighliteEnglishLetters": "Resaltar letras en inglés",
        "HighliteEnglishLettersDescription": "Resaltar letras en inglés en los titulares (útil si las noticias no están en inglés)",
        "HighliteEnglishLettersColor": "Color de letras en inglés resaltadas (predeterminado: #ffffff)",
        "HighliteNumbers": "Resaltar números",
        "HighliteNumbersDescription": "Resaltar números en los titulares",
        "HighliteNumbersColor": "Color de números resaltados (predeterminado: #ffffff)",
        "HighliteQuotes": "Resaltar texto entre comillas",
        "HighliteQuotesDescription": "Resaltar texto entre comillas en los titulares",
        "HighliteQuotesColor": "Color del texto entre comillas resaltado (predeterminado: #ffffff)",
        "ImagesHeight": "Altura de imágenes",
        "ImagesHeightDescription": "Si las imágenes se muestran incorrectamente, establece otro valor aquí (probablemente necesitas 175) (predeterminado 135)",
        "RSSFeedLink": "Enlace del feed RSS",
        "RSSFeedLinkDescription": "Selecciona una fuente de noticias. Puedes introducirla manualmente seleccionando la opción 'otro'",
        "CustomRSSLink": "Enlace RSS personalizado",
        "CustomRSSLinkDescription": "Puedes insertar tu propio enlace de fuente RSS. Si algo no se muestra correctamente, notifícalo al desarrollador del plugin.",
        "Other": "otro",
        "RSSNewsTitle": "Noticia RSS",
        "UpdateRSSNews": "Actualizar noticias RSS",
        "ScrollSpeed": "Velocidad de desplazamiento",
        "ScrollSpeedDescription": "Velocidad del desplazamiento horizontal automático del feed de Novedades (0 desactiva el desplazamiento automático, máximo 10)"
      },
      "PortugueseBrazil": {
        "languageName": "Português (Brasil)",
        "LanguageOfPlugin": "Idioma do plugin",
        "NewsCount": "Quantidade de notícias",
        "NewsCountDescription": "Quantos blocos de notícias RSS são exibidos no feed",
        "AlternateEveryNBlocks": "Alternar notícias RSS e notícias normais da Steam a cada N blocos",
        "AlternateEveryNBlocksDescription": "Intervalo entre notícias RSS e notícias da Steam",
        "NewsBlocksRange": "Quantidade de blocos consecutivos de notícias RSS",
        "NewsBlocksRangeDescription": "Quantidade de blocos consecutivos de notícias RSS para inserir",
        "HighliteEnglishLetters": "Destacar letras em inglês",
        "HighliteEnglishLettersDescription": "Destacar letras em inglês nos títulos (útil se as notícias não estiverem em inglês)",
        "HighliteEnglishLettersColor": "Cor das letras em inglês destacadas (padrão: #ffffff)",
        "HighliteNumbers": "Destacar números",
        "HighliteNumbersDescription": "Destacar números nos títulos",
        "HighliteNumbersColor": "Cor dos números destacados (padrão: #ffffff)",
        "HighliteQuotes": "Destacar texto entre aspas",
        "HighliteQuotesDescription": "Destacar texto entre aspas nos títulos",
        "HighliteQuotesColor": "Cor do texto entre aspas destacado (padrão: #ffffff)",
        "ImagesHeight": "Altura das imagens",
        "ImagesHeightDescription": "Se as imagens forem exibidas incorretamente, defina outro valor aqui (provavelmente você precisa de 175) (padrão 135)",
        "RSSFeedLink": "Link do feed RSS",
        "RSSFeedLinkDescription": "Selecione uma fonte de notícias. Pode ser inserida manualmente escolhendo a opção 'outro'",
        "CustomRSSLink": "Link RSS personalizado",
        "CustomRSSLinkDescription": "Você pode inserir seu próprio link de fonte RSS. Se algo não for exibido corretamente, avise o desenvolvedor do plugin.",
        "Other": "outro",
        "RSSNewsTitle": "Notícia RSS",
        "UpdateRSSNews": "Atualizar notícias RSS",
        "ScrollSpeed": "Velocidade de rolagem",
        "ScrollSpeedDescription": "Velocidade da rolagem horizontal automática do feed de Novidades (0 desativa a rolagem automática, máximo 10)"
      },
      "German": {
        "languageName": "Deutsch",
        "LanguageOfPlugin": "Plugin-Sprache",
        "NewsCount": "Anzahl der Nachrichten",
        "NewsCountDescription": "Wie viele RSS-Nachrichtenblöcke im Feed angezeigt werden",
        "AlternateEveryNBlocks": "RSS-Nachrichten und normale Steam-Nachrichten alle N Blöcke abwechseln",
        "AlternateEveryNBlocksDescription": "Intervall zwischen RSS-Nachrichten und Steam-Nachrichten",
        "NewsBlocksRange": "Anzahl aufeinanderfolgender RSS-Nachrichtenblöcke",
        "NewsBlocksRangeDescription": "Anzahl aufeinanderfolgender RSS-Nachrichtenblöcke zum Einfügen",
        "HighliteEnglishLetters": "Englische Buchstaben hervorheben",
        "HighliteEnglishLettersDescription": "Englische Buchstaben in Überschriften hervorheben (nützlich, wenn die Nachrichten nicht auf Englisch sind)",
        "HighliteEnglishLettersColor": "Farbe der hervorgehobenen englischen Buchstaben (Standard: #ffffff)",
        "HighliteNumbers": "Zahlen hervorheben",
        "HighliteNumbersDescription": "Zahlen in Überschriften hervorheben",
        "HighliteNumbersColor": "Farbe der hervorgehobenen Zahlen (Standard: #ffffff)",
        "HighliteQuotes": "Text in Anführungszeichen hervorheben",
        "HighliteQuotesDescription": "Text in Anführungszeichen in Überschriften hervorheben",
        "HighliteQuotesColor": "Farbe des hervorgehobenen Textes in Anführungszeichen (Standard: #ffffff)",
        "ImagesHeight": "Bildhöhe",
        "ImagesHeightDescription": "Wenn deine Bilder falsch dargestellt werden, setze hier einen anderen Wert (wahrscheinlich 175) (Standard 135)",
        "RSSFeedLink": "RSS-Feed-Link",
        "RSSFeedLinkDescription": "Nachrichtenquelle auswählen. Kann manuell eingegeben werden, wenn die Option 'andere' gewählt wird",
        "CustomRSSLink": "Benutzerdefinierter RSS-Link",
        "CustomRSSLinkDescription": "Du kannst deinen eigenen RSS-Quellenlink einfügen. Wenn etwas nicht korrekt angezeigt wird, informiere bitte den Plugin-Entwickler.",
        "Other": "andere",
        "RSSNewsTitle": "RSS-Nachricht",
        "UpdateRSSNews": "RSS-Nachrichten aktualisieren",
        "ScrollSpeed": "Scrollgeschwindigkeit",
        "ScrollSpeedDescription": "Geschwindigkeit des automatischen horizontalen Scrollens im Feed „Neuigkeiten“ (0 deaktiviert das automatische Scrollen, maximal 10)"
      },
      "French": {
        "languageName": "Français",
        "LanguageOfPlugin": "Langue du plugin",
        "NewsCount": "Nombre de nouvelles",
        "NewsCountDescription": "Combien de blocs d'actualités RSS sont affichés dans le flux",
        "AlternateEveryNBlocks": "Alterner les actualités RSS et les actualités Steam classiques tous les N blocs",
        "AlternateEveryNBlocksDescription": "Intervalle entre les actualités RSS et les actualités Steam",
        "NewsBlocksRange": "Nombre de blocs d'actualités RSS consécutifs",
        "NewsBlocksRangeDescription": "Nombre de blocs d'actualités RSS consécutifs à insérer",
        "HighliteEnglishLetters": "Mettre en évidence les lettres anglaises",
        "HighliteEnglishLettersDescription": "Mettre en évidence les lettres anglaises dans les titres (utile si les actualités ne sont pas en anglais)",
        "HighliteEnglishLettersColor": "Couleur des lettres anglaises mises en évidence (par défaut : #ffffff)",
        "HighliteNumbers": "Mettre en évidence les nombres",
        "HighliteNumbersDescription": "Mettre en évidence les nombres dans les titres",
        "HighliteNumbersColor": "Couleur des nombres mis en évidence (par défaut : #ffffff)",
        "HighliteQuotes": "Mettre en évidence le texte entre guillemets",
        "HighliteQuotesDescription": "Mettre en évidence le texte entre guillemets dans les titres",
        "HighliteQuotesColor": "Couleur du texte entre guillemets mis en évidence (par défaut : #ffffff)",
        "ImagesHeight": "Hauteur des images",
        "ImagesHeightDescription": "Si les images s'affichent incorrectement, définissez une autre valeur ici (vous avez probablement besoin de 175) (par défaut 135)",
        "RSSFeedLink": "Lien du flux RSS",
        "RSSFeedLinkDescription": "Sélection de la source d'actualités. Peut être saisi manuellement en choisissant l'option 'autre'",
        "CustomRSSLink": "Lien RSS personnalisé",
        "CustomRSSLinkDescription": "Vous pouvez insérer votre propre lien de source RSS. Si quelque chose ne s'affiche pas correctement, veuillez en informer le développeur du plugin.",
        "Other": "autre",
        "RSSNewsTitle": "Actualité RSS",
        "UpdateRSSNews": "Mettre à jour les actualités RSS",
        "ScrollSpeed": "Vitesse de défilement",
        "ScrollSpeedDescription": "Vitesse du défilement horizontal automatique du flux Nouveautés (0 désactive le défilement automatique, maximum 10)"
      },
      "Japanese": {
        "languageName": "日本語",
        "LanguageOfPlugin": "プラグインの言語",
        "NewsCount": "ニュース件数",
        "NewsCountDescription": "フィードに表示する RSS ニュースブロックの数",
        "AlternateEveryNBlocks": "N ブロックごとに RSS ニュースと通常の Steam ニュースを交互に表示",
        "AlternateEveryNBlocksDescription": "RSS ニュースと Steam ニュースの間隔",
        "NewsBlocksRange": "連続して挿入する RSS ニュースブロック数",
        "NewsBlocksRangeDescription": "挿入する連続 RSS ニュースブロックの数",
        "HighliteEnglishLetters": "英字をハイライト",
        "HighliteEnglishLettersDescription": "見出し内の英字をハイライトする（ニュースが英語でない場合に便利）",
        "HighliteEnglishLettersColor": "英字ハイライトの色（デフォルト: #ffffff）",
        "HighliteNumbers": "数字をハイライト",
        "HighliteNumbersDescription": "見出し内の数字をハイライトする",
        "HighliteNumbersColor": "数字ハイライトの色（デフォルト: #ffffff）",
        "HighliteQuotes": "引用符内のテキストをハイライト",
        "HighliteQuotesDescription": "見出し内の引用符で囲まれたテキストをハイライトする",
        "HighliteQuotesColor": "引用符内テキストのハイライト色（デフォルト: #ffffff）",
        "ImagesHeight": "画像の高さ",
        "ImagesHeightDescription": "画像が正しく表示されない場合は、ここで別の値を設定してください（おそらく 175 が必要です）（デフォルト 135）",
        "RSSFeedLink": "RSS フィードリンク",
        "RSSFeedLinkDescription": "ニュースソースを選択します。'other' オプションを選ぶと手動入力できます",
        "CustomRSSLink": "カスタム RSS リンク",
        "CustomRSSLinkDescription": "独自の RSS ソースリンクを入力できます。表示に問題がある場合は、プラグイン開発者にお知らせください。",
        "Other": "その他",
        "RSSNewsTitle": "RSS ニュース",
        "UpdateRSSNews": "RSS ニュースを更新",
        "ScrollSpeed": "スクロール速度",
        "ScrollSpeedDescription": "「最新情報」フィードの自動横スクロール速度（0 で自動スクロールを無効化、最大 10）"
      },
      "Korean": {
        "languageName": "한국어",
        "LanguageOfPlugin": "플러그인 언어",
        "NewsCount": "뉴스 개수",
        "NewsCountDescription": "피드에 표시되는 RSS 뉴스 블록 수",
        "AlternateEveryNBlocks": "N개 블록마다 RSS 뉴스와 일반 Steam 뉴스를 번갈아 표시",
        "AlternateEveryNBlocksDescription": "RSS 뉴스와 Steam 뉴스 사이 간격",
        "NewsBlocksRange": "연속 RSS 뉴스 블록 수",
        "NewsBlocksRangeDescription": "삽입할 연속 RSS 뉴스 블록 수",
        "HighliteEnglishLetters": "영문자 강조",
        "HighliteEnglishLettersDescription": "제목에서 영문자를 강조 표시합니다(뉴스가 영어가 아닐 때 유용)",
        "HighliteEnglishLettersColor": "영문자 강조 색상(기본값: #ffffff)",
        "HighliteNumbers": "숫자 강조",
        "HighliteNumbersDescription": "제목에서 숫자를 강조 표시합니다",
        "HighliteNumbersColor": "숫자 강조 색상(기본값: #ffffff)",
        "HighliteQuotes": "따옴표 안 텍스트 강조",
        "HighliteQuotesDescription": "제목에서 따옴표로 묶인 텍스트를 강조 표시합니다",
        "HighliteQuotesColor": "따옴표 안 텍스트 강조 색상(기본값: #ffffff)",
        "ImagesHeight": "이미지 높이",
        "ImagesHeightDescription": "이미지가 올바르게 표시되지 않으면 여기에서 다른 값을 설정하세요(아마 175가 필요합니다) (기본값 135)",
        "RSSFeedLink": "RSS 피드 링크",
        "RSSFeedLinkDescription": "뉴스 소스를 선택합니다. 'other' 옵션을 선택하면 수동 입력할 수 있습니다",
        "CustomRSSLink": "사용자 지정 RSS 링크",
        "CustomRSSLinkDescription": "직접 RSS 소스 링크를 넣을 수 있습니다. 올바르게 표시되지 않으면 플러그인 개발자에게 알려주세요.",
        "Other": "기타",
        "RSSNewsTitle": "RSS 뉴스",
        "UpdateRSSNews": "RSS 뉴스 업데이트",
        "ScrollSpeed": "스크롤 속도",
        "ScrollSpeedDescription": "\"새 소식\" 피드의 자동 가로 스크롤 속도(0이면 자동 스크롤 비활성화, 최대 10)"
      },
      "Turkish": {
        "languageName": "Türkçe",
        "LanguageOfPlugin": "Eklenti dili",
        "NewsCount": "Haber sayısı",
        "NewsCountDescription": "Akışta gösterilecek RSS haber bloğu sayısı",
        "AlternateEveryNBlocks": "RSS haberleri ile normal Steam haberlerini her N blokta bir dönüşümlü göster",
        "AlternateEveryNBlocksDescription": "RSS haberleri ile Steam haberleri arasındaki aralık",
        "NewsBlocksRange": "Art arda gelen RSS haber bloğu sayısı",
        "NewsBlocksRangeDescription": "Eklenecek ardışık RSS haber bloğu sayısı",
        "HighliteEnglishLetters": "İngilizce harfleri vurgula",
        "HighliteEnglishLettersDescription": "Başlıklardaki İngilizce harfleri vurgula (haberler İngilizce değilse faydalıdır)",
        "HighliteEnglishLettersColor": "Vurgulanan İngilizce harflerin rengi (varsayılan: #ffffff)",
        "HighliteNumbers": "Sayıları vurgula",
        "HighliteNumbersDescription": "Başlıklardaki sayıları vurgula",
        "HighliteNumbersColor": "Vurgulanan sayıların rengi (varsayılan: #ffffff)",
        "HighliteQuotes": "Tırnak içindeki metni vurgula",
        "HighliteQuotesDescription": "Başlıklarda tırnak içine alınmış metni vurgula",
        "HighliteQuotesColor": "Vurgulanan tırnak içi metnin rengi (varsayılan: #ffffff)",
        "ImagesHeight": "Görsel yüksekliği",
        "ImagesHeightDescription": "Görseller yanlış görüntüleniyorsa burada farklı bir değer ayarlayın (muhtemelen 175 gerekir) (varsayılan 135)",
        "RSSFeedLink": "RSS besleme bağlantısı",
        "RSSFeedLinkDescription": "Bir haber kaynağı seçin. 'diğer' seçeneğini seçerek elle girebilirsiniz",
        "CustomRSSLink": "Özel RSS bağlantısı",
        "CustomRSSLinkDescription": "Kendi RSS kaynak bağlantınızı ekleyebilirsiniz. Bir şey doğru görüntülenmiyorsa lütfen eklenti geliştiricisine bildirin.",
        "Other": "diğer",
        "RSSNewsTitle": "RSS Haberi",
        "UpdateRSSNews": "RSS haberlerini güncelle",
        "ScrollSpeed": "Kaydırma hızı",
        "ScrollSpeedDescription": "\"Yenilikler\" akışının otomatik yatay kaydırma hızı (0 otomatik kaydırmayı devre dışı bırakır, maksimum 10)"
    },
};